config/routes.rb
Rails.application.routes.draw do

  root :to => redirect("/usuarios/sign_in")

  devise_for :usuarios, :skip => :registrations

  as :usuario do
    get 'usuarios/edit' => 'registrations#edit', :as => 'edit_usuario_registration'
    put 'usuarios' => 'registrations#update', :as => 'usuario_registration'
  end

  resources :usuarios
  resources :animals
end

app/models/animal.rb
class Animal < ActiveRecord::Base

  enum especie: { arara: 1, cachorro: 2, capivara: 3, gato: 4, papagaio: 5 }

  validates :especie, presence: true
  validates :peso, numericality: { greater_than: 0 }, allow_nil: true
  validates :data_registro, presence: true
  validates_date :data_registro
  validates_date :data_saida, after: :data_registro, allow_blank: true

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  devise :database_authenticatable, :registerable,# :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  enum perfil: { administrador: 1, atendente: 2 }

  validates :nome, presence: true, format: { with: /[\w]+([\s]+[\w]+){1}+/ }
  validates :perfil, presence: true
  validates :data_registro, presence: true

  validates_date :data_desligamento, after: :data_registro, allow_blank: true

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :authenticate_usuario!

  ANIMAL_PARAMS = [:nome, :peso, :especie, :data_registro, :data_saida]

  expose(:animals)
  expose(:animal, attributes: :animal_params)

  def create
    if animal.save
      flash[:notice] = t('.success', nome: animal.nome)
      redirect_to animals_path
    else
      flash[:alert] = t('.failure')
      render :new
    end
  end

  def update
    if animal.save
      flash[:notice] = t('.success', nome: animal.nome)
      redirect_to animals_path
    else
      flash[:alert] = t('.failure', nome: animal.nome)
      render :edit
    end
  end

  def destroy
    if animal.destroy
      flash[:notice] = t('.success', nome: animal.nome)
    end
    redirect_to animals_path
  end

  private

  def animal_params
    params.require(:animal).permit(ANIMAL_PARAMS)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  def after_sign_in_path_for(usuario)
    animals_path
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def account_update_params
    params.require(:usuario).permit(
      :nome,
      :email,
      :password,
      :password_confirmation,
      :current_password)
  end

end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :authenticate_usuario!
  before_filter :check_admin!

  USUARIO_PARAMS = [:nome, :email, :password, :data_registro,
                    :data_desligamento, :perfil]

  expose(:usuarios)
  expose(:usuario, attributes: :usuario_params)

  def index
    if params[:perfil]
      self.usuarios = Usuario.where(perfil: params[:perfil]) unless params[:perfil] == ""
    end
  end

  def create
    usuario.password = t('.default_password')
    if usuario.save
      flash[:notice] = t('.success', nome: usuario.nome)
      redirect_to usuarios_path
    else
      flash[:alert] = t('.failure')
      render :new
    end
  end

  def update
    if usuario.save
      flash[:notice] = t('.success', nome: usuario.nome)
      redirect_to usuarios_path
    else
      flash[:alert] = t('.failure', nome: Usuario.find(usuario.id).nome)
      render :edit
    end
  end

  def destroy
    if usuario.destroy
      flash[:notice] = t('.success', nome: usuario.nome)
    else
      flash[:alert] = t('.failure', nome: usuario.nome)
    end
    redirect_to usuarios_path
  end

  private

  def usuario_params
    params.require(:usuario).permit(USUARIO_PARAMS)
  end

  def check_admin!
    unless current_usuario.administrador?
      flash[:alert] = t('.permission_denied')
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/_form.html.haml
%script
  $(function() { $('.datepicker').datepicker() });

- if animal.errors.any?
  %ul
    - animal.errors.each do |atributo, mensagem|
      %li
        %strong= "#{ Usuario.human_attribute_name(atributo) }:"
        = "#{ mensagem }"
  %br

= form_for animal, html: { class: "form form-horizontal animal" } do |f|
  .form-group
    = f.label :nome, class: 'control-label'
    .controls
      = f.text_field :nome, class: 'form-control'
    = error_span(animal[:nome])
  .form-group
    = f.label :peso, class: 'control-label'
    .controls
      = f.text_field :peso, class: 'form-control'
    = error_span(animal[:peso])
  .form-group
    = f.label :especie, class: 'control-label'
    .controls
      = f.select(:especie, Animal.especies.keys, {}, { class: "form-control" })
    %br/
  .form-group
    = f.label :data_registro, class: 'control-label'
    .controls
      = f.text_field :data_registro, class: ' datepicker form-control'
    = error_span(animal[:data_registro])
  .form-group
    = f.label :data_saida, class: 'control-label'
    .controls
      = f.text_field :data_saida, class: 'datepicker form-control'

  = f.submit nil,class: 'btn btn-primary', value: t('helpers.links.save')
  = link_to t("helpers.links.cancel"), animals_path, class: 'btn btn-default'

app/views/animals/edit.html.haml
- model_class = Animal

.container
  .row
    .col-md-11

      .page-header
        %h1=t "helpers.titles.edit", model: model_class.model_name.human

      .row
        .col-md-6.col-md-offset-3
          = render "form"

app/views/animals/index.html.haml
- model_class = Animal

.container
  .row
    .col-md-11

      .page-header
        %h1=t("helpers.titles.animals")

      %table.table.table-striped
        %thead
          %tr
            %th= model_class.human_attribute_name(:nome)
            %th= model_class.human_attribute_name(:peso)
            %th= model_class.human_attribute_name(:especie)
            %th= model_class.human_attribute_name(:data_registro)
            %th= model_class.human_attribute_name(:data_saida)
            %th= t("helpers.actions")
        %tbody
          - animals.each do |animal|
            %tr
              %td= link_to animal.nome, animal_path(animal)
              %td= animal.peso
              %td= animal.especie
              %td= animal.data_registro
              %td= animal.data_saida
              %td
                = link_to t("helpers.links.edit"),                            |
                  edit_animal_path(animal), class: 'btn btn-default btn-xs'

                = link_to t("helpers.links.destroy"),                         |
                  animal_path(animal), method: :delete,                       |
                    data: { confirm: t("helpers.links.confirm") },            |
                  class: 'btn btn-xs btn-danger'

      = link_to t("helpers.links.new"), new_animal_path,                      |
        class: 'btn btn-primary'

app/views/animals/new.html.haml
- model_class = Animal

.container
  .row
    .col-md-11

      .page-header
        %h1=t "helpers.titles.new", model: model_class.model_name.human

      .row
        .col-md-6.col-md-offset-3
          = render "form"

app/views/animals/show.html.haml
- model_class = Animal

.container
  .row
    .col-md-11

      .page-header
        %h1=t model_class.model_name.human

      %p
        %strong= model_class.human_attribute_name(:nome) + ':'
        %br
        = animal.nome
      %p
        %strong= model_class.human_attribute_name(:peso) + ':'
        %br
        = animal.peso

      %p
        %strong= model_class.human_attribute_name(:especie) + ':'
        %br
        = animal.especie

      %p
        %strong= model_class.human_attribute_name(:data_registro) + ':'
        %br
        = animal.data_registro
      %p
        %strong= model_class.human_attribute_name(:data_saida) + ':'
        %br
        = animal.data_saida


      = link_to t("helpers.links.back"), animals_path,                    |
        class: 'btn btn-default'

      = link_to t("helpers.links.edit"),                                  |
        edit_animal_path(animal), class: 'btn btn-default'

      = link_to t("helpers.links.destroy"), animal_path(animal),          |
        method: "delete", data: { confirm: t("helpers.links.confirm") },  |
        class: 'btn btn-danger'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Sistema para Gestão e Resgate de Animais
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .container-fluid
        %ul.nav.navbar-nav

          - if current_usuario.present?

            - if current_usuario.administrador?
              %li.dropdown
                %a.dropdown-toggle{'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-toggle' => 'dropdown', :href => '#', :role => 'button'}
                  = t '.usuarios'
                  %span.caret
                %ul.dropdown-menu
                  %li
                    = link_to t('.ver_usuarios'), usuarios_path
                  %li.divider{role: 'separator'}
                  %li
                    = link_to t('.novo_usuario'), new_usuario_path
            %li.dropdown
              %a.dropdown-toggle{'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-toggle' => 'dropdown', :href => '#', :role => 'button'}
                = t '.animals'
                %span.caret
              %ul.dropdown-menu
                %li
                  = link_to t('.ver_animais'), animals_path
                %li.divider{role: 'separator'}
                %li
                  = link_to t('.novo_animal'), new_animal_path


        .navbar-header.pull-right
          - if usuario_signed_in?
            = link_to t('.trocar_senha'),                  |
              edit_usuario_registration_path,                    |
              class: 'btn btn-sm btn-default navbar-btn'

            = link_to destroy_usuario_session_path,              |
              class: 'btn btn-sm btn-default navbar-btn',     |
              method: :delete do
              = fa_icon 'sign-out'
              Logout
          - else
            = link_to new_usuario_session_path,                |
              class: 'btn btn-sm btn-default navbar-btn' do
              = fa_icon 'sign-in'
              Login

    - if notice || alert
      .row.text-center
        .alert.col-md-4.col-md-offset-4
          - if notice
            .alert.alert-success= notice
          - if alert
            .alert.alert-danger= alert
    = yield

app/views/usuarios/_form.html.haml
%script
  $(function() { $('.datepicker').datepicker() });

- if usuario.errors.any?
  %ul
    - usuario.errors.each do |atributo, mensagem|
      %li
        %strong= "#{ Usuario.human_attribute_name(atributo) }:"
        = "#{ mensagem }"

= form_for usuario, html: { class: "form form-horizontal usuario" } do |f|
  .form-group
    = f.label :nome, class: 'control-label'
    .controls
      = f.text_field :nome, class: 'form-control', required: true
    = error_span(usuario[:nome])
  .form-group
    = f.label :email, class: 'control-label'
    .controls
      = f.text_field :email, class: 'form-control', required: true

  .form-group
    = f.label :data_registro, class: 'control-label'
    .controls
      = f.text_field :data_registro, class: ' datepicker form-control'
    = error_span(usuario[:data_registro])

  .form-group
    = f.label :data_desligamento, class: 'control-label'
    .controls
      = f.text_field :data_desligamento, class: 'datepicker form-control'

  .form-group
    = f.label :perfil, class: 'control-label'
    .controls
      = f.select(:perfil, Usuario.perfils.keys, {}, { class: "form-control" })
    %br/

  = f.submit t('helpers.links.save'), class: 'btn btn-primary'

  = link_to t("helpers.links.cancel"), usuarios_path, class: 'btn btn-default'
  %br
  %br

app/views/usuarios/edit.html.haml
- model_class = Usuario

.container
  .row
    .col-md-11

      .page-header
        %h1=t "helpers.titles.edit", model: model_class.model_name.human

      .row
        .col-md-6.col-md-offset-3
          = render "form"

app/views/usuarios/index.html.haml
- model_class = Usuario

.container
  .row
    .col-md-11

      .page-header
        %h1=t model_class.model_name.human.pluralize
      %br

      = form_tag("/usuarios/", method: "get") do
        = label_tag :perfil
        = select_tag(:perfil, options_for_select([['Todos', ''],['Administrador', 1], ['Atendente', 2]], params[:perfil]))
        = submit_tag "Visualizar"
      %br


      %table.table.table-striped
        %thead
          %tr
            %th= model_class.human_attribute_name(:nome)
            %th= model_class.human_attribute_name(:email)
            %th= model_class.human_attribute_name(:data_registro)
            %th= model_class.human_attribute_name(:data_desligamento)
            %th= model_class.human_attribute_name(:perfil)
            %th= t("helpers.actions")
        %tbody
          - usuarios.each do |usuario|
            %tr
              %td= link_to usuario.nome, usuario_path(usuario)
              %td= usuario.email
              %td= usuario.data_registro
              %td= usuario.data_desligamento
              %td= usuario.perfil
              %td
                = link_to t("helpers.links.edit"),                            |
                  edit_usuario_path(usuario), class: 'btn btn-default btn-xs'

                = link_to t("helpers.links.destroy"),                         |
                  usuario_path(usuario), method: :delete,                     |
                    data: { confirm: t("helpers.links.confirm") },            |
                  class: 'btn btn-xs btn-danger'

      = link_to t("helpers.links.new"), new_usuario_path,                     |
        class: 'btn btn-primary'

app/views/usuarios/new.html.haml
- model_class = Usuario

.container
  .row
    .col-md-11

      .page-header
        %h1=t "helpers.titles.new", model: model_class.model_name.human

      .row
        .col-md-6.col-md-offset-3
          = render "form"

app/views/usuarios/show.html.haml
- model_class = Usuario

.container
  .row
    .col-md-11

      .page-header
        %h1=t model_class.model_name.human

      %p
        %strong= model_class.human_attribute_name(:nome) + ':'
        %br
        = usuario.nome
      %p
        %strong= model_class.human_attribute_name(:email) + ':'
        %br
        = usuario.email
      %p
        %strong= model_class.human_attribute_name(:data_registro) + ':'
        %br
        = usuario.data_registro
      %p
        %strong= model_class.human_attribute_name(:data_desligamento) + ':'
        %br
        = usuario.data_desligamento
      %p
        %strong= model_class.human_attribute_name(:perfil) + ':'
        %br
        = usuario.perfil


      = link_to t("helpers.links.back"), usuarios_path,                  |
        class: 'btn btn-default'

      = link_to t("helpers.links.edit"),                                 |
        edit_usuario_path(usuario), class: 'btn btn-default'

      = link_to t("helpers.links.destroy"), usuario_path(usuario),       |
        method: "delete", data: { confirm: t("helpers.links.confirm") }, |
        class: 'btn btn-danger'